# Welcome to Jekyll!

# Website settings
title: darteaga94
description: Dinier's blog,use Jekyll and github pages.
keywords: Jack,Jalpc,blog,Jekyll,github,gh-pages
baseurl: https://jarrekk.github.io/Jalpc
url: http://www.jarrekk.com
# url: http://127.0.0.1:4000
img_path: /Jalpc/static/assets/img/landing/header_one.jpg

# author
author:
  name: darteaga94
  first_name: Dinier
  last_name: Arteaga Miranda
  cv: http://cv.jarrekk.com
  email: darteaga94@gmail.com
  facebook_username: darteaga94
  github_username: darteaga94
  linkedin_id: darteaga94
  avatar: https://avatars1.githubusercontent.com/u/7543761?s=460&v=4
  skill_icon1:
    - name: icon-python
    - name: icon-shell
  skill_icon2:
    - name: icon-mongodb
    - name: icon-docker
  desc: I am a Full Stack engineer with website development, automation Ops and writing scripts experience. Life is a continuous learning process, so work makes me more rigorous, travel makes my life more colorful. I can make lots of friends when I coding and travel.

# comment
disqus:
  name: jalpc

# analytics
## google analytics
ga:
  id: UA-93473370-1

go:
  id: GTM-NHMS8GD

## growingIO
gio:
  # id: a49d4901c7853da9

## donation
donation: on

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
